export const EN_MEMBERS = [
  'Arya Kuroha',
  'Jira Jisaki',
  'Remia Aotsuki',
  'Riko Solari',
  'Narin Mikure',
  'Juno Umezono',
  '梅園ジュノ',
  '梅園Juno',
]

export const TWITCH_CHANNEL_MAPPING: Record<string, string> = {
  '花芽すみれ': 'kagasumire',
  '花芽なずな': 'nazunakaga',
  '一ノ瀬うるは': 'ichinose_uruha',
  '胡桃のあ': 'kurumi_noa',
  '橘ひなの': 'hinano_tachiba7',
  '兎咲ミミ': 'tosaki_mimi',
  '空澄セナ': 'asumisena',
  '英リサ': 'lisahanabusa',
  '八雲べに': 'yakumo_beni',
  '小森めと': 'met_komori',
  '神成きゅぴ': 'kaminariqpi',
  '猫汰つな': 'tsuna_nekota',
  '紫宮るな': 'shinomiya_runa',
  '白波らむね': 'ramune_shiranami',
  '如月れん': 'ren_kisaragi',
  '藍沢エマ': 'ema_aizawa',
  '夢野あかり': 'akarindao',
  '夜乃くろむ': 'kuromu_yano',
  '紡木こかげ': 'kokage_tsumugi',
  '千燈ゆうひ': 'yuuhi_sendo',
  '銀城サイネ': 'saine_ginjo',
  '龍巻ちせ': 'chise_tatsumaki',
  '甘結もか': 'amayui_moka',
  'Arya Kuroha': 'aryakuroha',
  'Jira Jisaki': 'jirajisaki',
  'Remia Aotsuki': 'remiaaotsuki',
  'Riko Solari': 'rikosolari',
  'Narin Mikure': 'narinmikure',
  'Juno Umezono': 'juno_umezono',
  '梅園ジュノ': 'juno_umezono',
  '梅園Juno': 'juno_umezono',
}
